
.MODEL SMALL ;TIENE LA INTENCION DE UTILIZAR EL MODELO DE MEMORIA PEQUENA 
  
.STACK 100   ;APILACION DE UNA CADENA 
    
.DATA        ;CONTENIDO GUARDADO

MSG DB ' Hola mundo cruel  :(  $'  ;CADENA DE CARACTERES

.CODE        ;ETIQUETA DEL CODIGO

;INICIALIZACION DE LAS VARIABLES

MOV AX, @DATA

MOV DS, AX
      
MOV AH, 09H ; FUNCION PARA IMPRIMIR UNA CADENA
      
LEA DX, MSG ;CARGA A "DX" CON LO QUE CONTENGA MSG

INT 21H ;IMPRIME LA CADENA

.EXIT

END