
;MODO GRAFICO
ORG 0100H

MOV AH, 0    ;CONFIGURACION DEL MODO

MOV AL, 13H  ;320x200 PX, 256 COLORES

INT 10H      ;SET DEL MODO

MOV AH, 0CH  ;CONFIGURACION PARA UN SOLO PIXEL

MOV AL, 0FH  ;CONFIGURACION DEL COLOR NEGRO

MOV CX, 10   ;COORDENADA DE LA COLUMNA "Y"

MOV DX, 10   ;COORDENADA DE LA COLUMNA "X"

INT 10H

LINEA:

        INC CX       ;INCREMENTO DE COORDENADA
        
        INT 10H      ;SETEO DE COLOR POR PIXEL
        
        CMP CX, 100  ;LIMITE 
        
        JNE LINEA    ;RETORNA LA OPERACION HASTA LLEGAR AL LIMITE
        
RET                                                        